algoritmo "Soma de 2 Números!"
var
          A: inteiro
          B,C: inteiro

inicio
          // Comando de Entrada
          Escreva("Digite o Primeiro Número: ")

          // Comando de Saída
          Leia(A)
          Escreva ("Digite o Segundo Número: ")
          Leia(B)

          // Processamento de Dados
          C <- A+B
          Escreva("O Resultado é ")
           // Fase Saída de Dados
              Escreva(c)

fimalgoritmo